# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSL_to_word_local.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSL2wordLocal(object):
    def setupUi(self, CSL2wordLocal):
        CSL2wordLocal.setObjectName("CSL2wordLocal")
        CSL2wordLocal.resize(889, 613)
        self.gridLayout_2 = QtWidgets.QGridLayout(CSL2wordLocal)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.result_show_label = QtWidgets.QLabel(CSL2wordLocal)
        self.result_show_label.setMinimumSize(QtCore.QSize(0, 0))
        self.result_show_label.setMaximumSize(QtCore.QSize(165, 40))
        self.result_show_label.setObjectName("result_show_label")
        self.gridLayout.addWidget(self.result_show_label, 1, 0, 1, 1)
        self.group_box = QtWidgets.QGroupBox(CSL2wordLocal)
        self.group_box.setMinimumSize(QtCore.QSize(0, 120))
        self.group_box.setMaximumSize(QtCore.QSize(165, 120))
        self.group_box.setObjectName("group_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.local_update_btn = QtWidgets.QPushButton(self.group_box)
        self.local_update_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.local_update_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.local_update_btn.setObjectName("local_update_btn")
        self.verticalLayout.addWidget(self.local_update_btn)
        self.info_clear_btn = QtWidgets.QPushButton(self.group_box)
        self.info_clear_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.info_clear_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.info_clear_btn.setObjectName("info_clear_btn")
        self.verticalLayout.addWidget(self.info_clear_btn)
        self.gridLayout.addWidget(self.group_box, 0, 0, 1, 1)
        self.result_show_browser = QtWidgets.QTextBrowser(CSL2wordLocal)
        self.result_show_browser.setMinimumSize(QtCore.QSize(0, 0))
        self.result_show_browser.setMaximumSize(QtCore.QSize(165, 16777215))
        self.result_show_browser.setObjectName("result_show_browser")
        self.gridLayout.addWidget(self.result_show_browser, 2, 0, 2, 1)
        self.cam_window = QtWidgets.QLabel(CSL2wordLocal)
        self.cam_window.setMinimumSize(QtCore.QSize(0, 0))
        self.cam_window.setObjectName("cam_window")
        self.gridLayout.addWidget(self.cam_window, 0, 1, 3, 1)
        self.progress_bar = QtWidgets.QProgressBar(CSL2wordLocal)
        self.progress_bar.setMinimumSize(QtCore.QSize(220, 15))
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(CSL2wordLocal)
        QtCore.QMetaObject.connectSlotsByName(CSL2wordLocal)

    def retranslateUi(self, CSL2wordLocal):
        _translate = QtCore.QCoreApplication.translate
        CSL2wordLocal.setWindowTitle(_translate("CSL2wordLocal", "Form"))
        self.result_show_label.setText(_translate("CSL2wordLocal", "预测结果"))
        self.group_box.setTitle(_translate("CSL2wordLocal", "本地上传"))
        self.local_update_btn.setText(_translate("CSL2wordLocal", "上传本地视频"))
        self.info_clear_btn.setText(_translate("CSL2wordLocal", "清除预测结果"))
        self.cam_window.setText(_translate("CSL2wordLocal", "等待开启摄像头..."))
