# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorSubmit(object):
    def setupUi(self, ErrorSubmit):
        ErrorSubmit.setObjectName("ErrorSubmit")
        ErrorSubmit.resize(659, 160)
        self.gridLayout_2 = QtWidgets.QGridLayout(ErrorSubmit)
        self.gridLayout_2.setContentsMargins(20, 14, 20, 18)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(547, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 3)
        self.minimize_btn = QtWidgets.QPushButton(ErrorSubmit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimize_btn.sizePolicy().hasHeightForWidth())
        self.minimize_btn.setSizePolicy(sizePolicy)
        self.minimize_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.minimize_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.minimize_btn.setText("")
        self.minimize_btn.setObjectName("minimize_btn")
        self.gridLayout.addWidget(self.minimize_btn, 0, 3, 1, 1)
        self.close_btn = QtWidgets.QPushButton(ErrorSubmit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.close_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.gridLayout.addWidget(self.close_btn, 0, 4, 1, 1)
        self.info_hint_label = QtWidgets.QLabel(ErrorSubmit)
        self.info_hint_label.setMinimumSize(QtCore.QSize(500, 50))
        self.info_hint_label.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI SC")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.info_hint_label.setFont(font)
        self.info_hint_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_hint_label.setTextFormat(QtCore.Qt.AutoText)
        self.info_hint_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.info_hint_label.setObjectName("info_hint_label")
        self.gridLayout.addWidget(self.info_hint_label, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(88, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 3)
        self.line_edit = QtWidgets.QLineEdit(ErrorSubmit)
        self.line_edit.setMinimumSize(QtCore.QSize(360, 45))
        self.line_edit.setMaximumSize(QtCore.QSize(360, 45))
        self.line_edit.setText("")
        self.line_edit.setCursorPosition(0)
        self.line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit.setObjectName("line_edit")
        self.gridLayout.addWidget(self.line_edit, 2, 0, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(ErrorSubmit)
        self.submit_btn.setMinimumSize(QtCore.QSize(250, 45))
        self.submit_btn.setMaximumSize(QtCore.QSize(250, 45))
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout.addWidget(self.submit_btn, 2, 1, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ErrorSubmit)
        QtCore.QMetaObject.connectSlotsByName(ErrorSubmit)

    def retranslateUi(self, ErrorSubmit):
        _translate = QtCore.QCoreApplication.translate
        ErrorSubmit.setWindowTitle(_translate("ErrorSubmit", "Form"))
        self.info_hint_label.setText(_translate("ErrorSubmit", "您认为当前视频对应的手语动作应该是："))
        self.line_edit.setPlaceholderText(_translate("ErrorSubmit", "请在这里输入词语"))
        self.submit_btn.setText(_translate("ErrorSubmit", "提交"))
