# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FirstDialog(object):
    def setupUi(self, FirstDialog):
        FirstDialog.setObjectName("FirstDialog")
        FirstDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        FirstDialog.resize(1600, 900)
        FirstDialog.setMinimumSize(QtCore.QSize(1600, 900))
        FirstDialog.setMaximumSize(QtCore.QSize(1600, 900))
        self.welcome_dialog = QtWidgets.QLabel(FirstDialog)
        self.welcome_dialog.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.welcome_dialog.setMinimumSize(QtCore.QSize(1600, 900))
        self.welcome_dialog.setMaximumSize(QtCore.QSize(1600, 900))
        self.welcome_dialog.setObjectName("welcome_dialog")
        self.close_btn = QtWidgets.QPushButton(FirstDialog)
        self.close_btn.setGeometry(QtCore.QRect(1370, 810, 140, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMinimumSize(QtCore.QSize(140, 50))
        self.close_btn.setMaximumSize(QtCore.QSize(140, 50))
        self.close_btn.setObjectName("close_btn")
        self.welcome_dialog.raise_()

        self.retranslateUi(FirstDialog)
        QtCore.QMetaObject.connectSlotsByName(FirstDialog)

    def retranslateUi(self, FirstDialog):
        _translate = QtCore.QCoreApplication.translate
        FirstDialog.setWindowTitle(_translate("FirstDialog", "Dialog"))
        self.welcome_dialog.setText(_translate("FirstDialog", "TextLabel"))
        self.close_btn.setText(_translate("FirstDialog", "开始使用"))
