# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'word_to_CSL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_word2CSL(object):
    def setupUi(self, word2CSL):
        word2CSL.setObjectName("word2CSL")
        word2CSL.resize(889, 613)
        self.gridLayout_2 = QtWidgets.QGridLayout(word2CSL)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.group_box = QtWidgets.QGroupBox(word2CSL)
        self.group_box.setMinimumSize(QtCore.QSize(0, 220))
        self.group_box.setMaximumSize(QtCore.QSize(165, 370))
        self.group_box.setObjectName("group_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_edit = QtWidgets.QLineEdit(self.group_box)
        self.line_edit.setMinimumSize(QtCore.QSize(130, 40))
        self.line_edit.setMaximumSize(QtCore.QSize(200, 60))
        self.line_edit.setText("")
        self.line_edit.setCursorPosition(0)
        self.line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit.setObjectName("line_edit")
        self.verticalLayout.addWidget(self.line_edit)
        self.word_search_btn = QtWidgets.QPushButton(self.group_box)
        self.word_search_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.word_search_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.word_search_btn.setObjectName("word_search_btn")
        self.verticalLayout.addWidget(self.word_search_btn)
        self.video_download_btn = QtWidgets.QPushButton(self.group_box)
        self.video_download_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.video_download_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.video_download_btn.setObjectName("video_download_btn")
        self.verticalLayout.addWidget(self.video_download_btn)
        self.dic_download_btn = QtWidgets.QPushButton(self.group_box)
        self.dic_download_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.dic_download_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.dic_download_btn.setObjectName("dic_download_btn")
        self.verticalLayout.addWidget(self.dic_download_btn)
        self.error_feedback_btn = QtWidgets.QPushButton(self.group_box)
        self.error_feedback_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.error_feedback_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.error_feedback_btn.setObjectName("error_feedback_btn")
        self.verticalLayout.addWidget(self.error_feedback_btn)
        self.gridLayout.addWidget(self.group_box, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.group_box_2 = QtWidgets.QGroupBox(word2CSL)
        self.group_box_2.setMinimumSize(QtCore.QSize(250, 410))
        self.group_box_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.group_box_2.setObjectName("group_box_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_box_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_hint_browser = QtWidgets.QTextBrowser(self.group_box_2)
        self.info_hint_browser.setMinimumSize(QtCore.QSize(0, 0))
        self.info_hint_browser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.info_hint_browser.setObjectName("Hint")
        self.verticalLayout_2.addWidget(self.info_hint_browser)
        self.gridLayout.addWidget(self.group_box_2, 0, 1, 2, 1)
        self.video_window = QtWidgets.QLabel(word2CSL)
        self.video_window.setMinimumSize(QtCore.QSize(400, 400))
        self.video_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.video_window.setSizeIncrement(QtCore.QSize(0, 0))
        self.video_window.setObjectName("video_window")
        self.gridLayout.addWidget(self.video_window, 0, 2, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(word2CSL)
        QtCore.QMetaObject.connectSlotsByName(word2CSL)

    def retranslateUi(self, word2CSL):
        _translate = QtCore.QCoreApplication.translate
        word2CSL.setWindowTitle(_translate("word2CSL", "Form"))
        self.group_box.setTitle(_translate("word2CSL", "单词表达"))
        self.line_edit.setPlaceholderText(_translate("word2CSL", "请在这里输入词语"))
        self.word_search_btn.setText(_translate("word2CSL", "查询手语动作"))
        self.video_download_btn.setText(_translate("word2CSL", "下载手语视频"))
        self.dic_download_btn.setText(_translate("word2CSL", "下载收录词语表"))
        self.error_feedback_btn.setText(_translate("word2CSL", "错误信息反馈"))
        self.group_box_2.setTitle(_translate("word2CSL", "友情提示"))
        self.video_window.setText(_translate("word2CSL", "   等待视频播放..."))
